name: flutter_user_state_notifier
description: "A Flutter package to manage user popups about your current app state"
version: 1.0.0

repository: https://github.com/Auja-Der-Freizeitplaner/flutter_user_state_notifier.git
homepage: https://auja.app/

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
